# Copyright 2016 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: libvips
  version: 8.5.4
  
source:
  fn: vips-8.5.4.tar.gz
  url: https://github.com/jcupitt/libvips/releases/download/v8.5.4/vips-8.5.4.tar.gz

build:
  number: 1
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    #- openslide-python 
    - gcc
    - python 3.5.*
    - glib 2.43.0
    - libxml2
    - zlib
   # - libgsf
    - libpng
    #- libexif
    - jpeg 9b
    - giflib
    - librsvg
    - libgsf
    - libtiff
 #   - fftw
    - cfitsio
    - libwebp
    - gobject-introspection
    - pygobject
    - pango
    - harfbuzz 1.0.6
    - libffi
    - libwebp
    - bzip2 1.0.6 4
    
  run:
    #- openslide-python
    - python
    - glib
    - libxml2
    - zlib
    #- libgsf
    - libpng
    #- libexif
    - jpeg 9b
    - giflib
    - librsvg
    - libgsf
    - libtiff
  #  - fftw
    - cfitsio
   # - libwebp
    - gobject-introspection
    - pygobject
    - pango
    - libffi
    - libwebp
    - bzip2 1.0.6 4

about:
  home: http://www.vips.ecs.soton.ac.uk/
  license: LGPL https://github.com/jcupitt/libvips/blob/master/COPYING
